add _drop key
mt-mods/controls pull request #6
Opened 2023-12-03 21:43 UTC by wsor4035

adds a _drop key event. note, cant override minetest.item_drop since this will cause double events for existing since it is defined in minetest.registered_nodes.

redo of https://github.com/mt-mods/controls/pull/5

2023-12-03 23:04 UTC, appgurueu requested changes
The overall implementation is rather intrusive / hacky IMO. I'm not sure if it's a good idea for modders to start overloading `drop`. The tradeoff here should be carefully considered.

2023-12-03 23:04 UTC, appgurueu commented on init.lua
> +            return old_node_drop(itemstack, dropper, unpack({...}))
This should be just `...` instead of `unpack({...})`. The latter handles `nil`s in `...` incorrectly (and is less efficient).

2023-12-03 23:04 UTC, appgurueu commented on init.lua
> +    function minetest.register_node(name, def)
What about `register_item` / `register_craftitem` / `register_tool`?

2023-12-03 23:04 UTC, appgurueu commented on init.lua
> +            def.on_drop = function(itemstack, dropper, ...)
Code duplication. Please just write a function `hook_on_drop(on_drop)` and use that everywhere. Then you could simply do `def.on_drop = hook_on_drop(def.on_drop)` end.

2023-12-04 06:00 UTC, wsor4035 commented on init.lua
> +            return old_node_drop(itemstack, dropper, unpack({...}))
fair enough, been a while since i used this pattern

2023-12-04 07:54 UTC, OgelGames commented
I think this is too hacky, and I'm not sure if it's even needed, `on_drop` should be enough in most cases.

2023-12-04 07:57 UTC, wsor4035 commented
> I think this is too hacky, and I'm not sure if it's even needed, `on_drop` should be enough in most cases.

🤷 if thats what wanted, is fine by me, just need to close the issue then (as well as this pr)

2023-12-04 08:05 UTC, closed without merging

2023-12-04 08:05 UTC, BuckarooBanzay commented
> edit: @BuckarooBanzay any opposition to closing this pr+issue since you upvoted it?

nope, do whatever you want with it :)